package main

func main() {
	//s1 := goDawggy.Bark()
	//s2 := goDawggy.Barks()
	//
	//fmt.Println(s1)
	//fmt.Println(s2)
	//basic.PrintStuffs()
	//flow.RollComparisonLogic()
	//flow.RollStatementIdiom()
	//flow.RollSwitchStatements()
	//flow.RollSelectStatements()
	//array_slice.RollArrays()
	//array_slice.RollIceCream()
	//array_slice.RollIceCreamSlice()
	//array_slice.RollSlices()
	//array_slice.RollSlicercises()
	//mappage.RollMappage()
	//mappage.RollMappercise()
	//structy_structs.RollStructercises()
	//funky_funcs.RollFunkyFuncs()
	//funky_funcs.RollDefer()
	//funky_funcs.RollMethods()
	//funky_funcs.RollInterfaces()
	//funky_funcs.RollWriteOut()
	//funky_funcs.RollByteBuffer()
	//funky_funcs.RollAnonymoose()
	//funky_funcs.RollFuncExpressions()
	//funky_funcs.RollCallbacks()
	//funky_funcs.RollClosure()
	//funky_funcs.RollRecursion()
	//funky_funcs.RollWrapper()
}
